export const TALENT_CANDIDATES = [
  {
    id: 1,
    name: 'Arjun Mehta',
    role: 'Full Stack Developer',
    matchScore: 92,
    lastActive: '2h ago',
    status: 'Active',
    isTopPick: true,
    isFastResponder: true,
    isFinalist: true,
    contactPreference: 'email',
    scoreBreakdown: {
      skills: 94,
      culture: 88,
      responsiveness: 95,
    },
    skills: ['React', 'Node', 'AWS'],
    rate: '$60/hr',
    exp: '5y',
    rating: 4.9,
    img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=240&q=80',
  },
  {
    id: 2,
    name: 'Sanya Iyer',
    role: 'UI/UX Designer',
    matchScore: 76,
    lastActive: '1d ago',
    status: 'Needs Follow-up',
    isTopPick: false,
    isFastResponder: true,
    isFinalist: true,
    contactPreference: 'whatsapp',
    scoreBreakdown: {
      skills: 80,
      culture: 74,
      responsiveness: 77,
    },
    skills: ['Figma', 'Framer', 'Adobe'],
    rate: '$45/hr',
    exp: '3y',
    rating: 5.0,
    img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=240&q=80',
  },
  {
    id: 3,
    name: 'Rohan Das',
    role: 'DevOps Engineer',
    matchScore: 48,
    lastActive: '6d ago',
    status: 'Dormant',
    isTopPick: false,
    isFastResponder: false,
    isFinalist: false,
    contactPreference: 'email',
    scoreBreakdown: {
      skills: 58,
      culture: 46,
      responsiveness: 40,
    },
    skills: ['Docker', 'K8s', 'GCP'],
    rate: '$80/hr',
    exp: '7y',
    rating: 4.8,
    img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=240&q=80',
  },
  {
    id: 4,
    name: 'Neha Kulkarni',
    role: 'Product Analyst',
    matchScore: 84,
    lastActive: '5h ago',
    status: 'Active',
    isTopPick: true,
    isFastResponder: false,
    isFinalist: true,
    contactPreference: 'whatsapp',
    scoreBreakdown: {
      skills: 82,
      culture: 90,
      responsiveness: 80,
    },
    skills: ['SQL', 'Mixpanel', 'A/B Testing'],
    rate: '$55/hr',
    exp: '4y',
    rating: 4.7,
    img: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=240&q=80',
  },
];
